services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}
        volumes:
            - type: bind
              source: ./.env
              target: /app/.env
            - .:/app
        restart: always
        working_dir: /app
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=r-p"
            - "traefik.http.routers.${APP_URL}.rule=Host(`${APP_DOMAIN}`)"
            - "traefik.http.routers.${APP_URL}.entrypoints=websecure,web"
            - "traefik.http.routers.${APP_URL}.tls=true"
            - "traefik.http.routers.${APP_URL}.tls.certresolver=myresolver"
            - "traefik.http.services.${APP_URL}.loadbalancer.server.port=80"
            - "traefik.http.middlewares.autodetect.contenttype=true"
            #- "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
            #- "traefik.http.routers.http${APP_URL}.entrypoints=web"
            - "traefik.http.routers.http${APP_URL}.rule=Host(`${APP_DOMAIN}`)"
        networks:
            - laravel
            - r-p
        environment:
            - "SERVER_NAME=:80"
        ports:
            - "87:80"
            - '448:443' 
            - '448:443/udp'

networks:
    laravel:
        driver: bridge
    r-p:
        external: true
